spring:
  profiles:
    active: dev # 배포용은 prod, 로컬용은 dev 로 바꿔 사용
  application:
    name: backend
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
aladin:
  api:
    key: ${ALADIN_API_KEY}
openai:
  api-key: ${OPENAI_API_KEY}
cloud:
  aws:
    s3:
      bucket: picky-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}


#naver:
#  client:
#    id: "네이버ClientId"
#    secret: "네이버ClientSecret"

jwt:
  secret: ${JWT_SECRET}
  access-token-expire-time: 1800000
  refresh-token-expire-time: 604800000
firebase:
  service-account-key-path: firebase-adminsdk.json
